[project]
name = "declivity"
version = "0.1.0"
description = "Unified benchmarking framework for evolutionary and quasi-Newton optimization algorithms (DES, CMA-ES, MF-CMA-ES, L-BFGS-B)"
authors = [
    {name = "Jedrzej Grabski", email = "grabski.dev@gmail.com"},
]
dependencies = ["setuptools>=80.4.0", "numpy>=2.2.5", "matplotlib>=3.10.3", "scipy>=1.15.3", "opfunu>=1.0.1", "seaborn>=0.13.2", "joblib>=1.5.3"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
run-example = "python -m experiments.basic.simple_optimization"
run-r = "python -m experiments.cross_validation.des_vs_r"
pyright = {cmd = "npx pyright", env = {}}

[tool.pdm]
distribution = false
